name: Code style

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  php-cs-fixer:
    name: PHP-CodeSniffer
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup PHP
        uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # 2.40.0
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Run codestyle
        run: composer run codestyle

      - name: Run psalm
        run: composer run psalm
